version: "3"

networks:
  golang:

services:
  # mysql:
  #   image: mysql:8.2.0
  #   container_name: mysql
  #   ports:
  #     - 13306:3306
  #   volumes:
  #         - mysql-data:/var/lib/mysql
  #         - "./mysql/:/docker-entrypoint-initdb.d/"
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: dbpass
  #     MYSQL_DATABASE: sklad
  #   networks:
  #     - golang

  # redis:
  #   image: redis:7.2.3-alpine3.18
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - golang

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.9-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      # - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - golang


volumes:
  mysql-data:
  rabbit-data: